name: coursity
services:
  database:
    image: postgres:17.2
    ports: [5432:5432]
    container_name: database
    hostname: database
    restart: always
    volumes: [database:/var/lib/postgresql/data]
    env_file: .env
    networks: [database]
    environment:
      POSTGRES_DB: coursity
      POSTGRES_USER: coursity_user
      POSTGRES_PASSWORD: coursity_user123!
  minio:
    image: bitnami/minio:2025.4.22
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123!
    volumes:
      - minio_data:/bitnami/minio/data
    networks:
      - minio

networks:
  database:
  minio:

volumes:
  database:
  minio_data:
